# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ssh_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1344, 778)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1370, 793))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_monitoring = QtWidgets.QFrame(self.tab_3)
        self.frame_monitoring.setGeometry(QtCore.QRect(0, -10, 1341, 751))
        self.frame_monitoring.setStyleSheet("QFrame\n"
"{\n"
"background:white;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"border:transperant;\n"
"border-bottom:1px solid black;\n"
"font-family:times;\n"
"font-size:16px;\n"
"}")
        self.frame_monitoring.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_monitoring.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_monitoring.setObjectName("frame_monitoring")
        self.tableWidget_Monitoring = QtWidgets.QTableWidget(self.frame_monitoring)
        self.tableWidget_Monitoring.setGeometry(QtCore.QRect(30, 130, 1301, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Monitoring.sizePolicy().hasHeightForWidth())
        self.tableWidget_Monitoring.setSizePolicy(sizePolicy)
        self.tableWidget_Monitoring.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget_Monitoring.setLineWidth(0)
        self.tableWidget_Monitoring.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget_Monitoring.setColumnCount(7)
        self.tableWidget_Monitoring.setObjectName("tableWidget_Monitoring")
        self.tableWidget_Monitoring.setRowCount(0)
        self.tableWidget_Monitoring.horizontalHeader().setDefaultSectionSize(183)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_monitoring)
        self.pushButton_8.setGeometry(QtCore.QRect(1350, 290, 151, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_cur_dev = QtWidgets.QLabel(self.frame_monitoring)
        self.label_cur_dev.setGeometry(QtCore.QRect(30, 100, 851, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_dev.setFont(font)
        self.label_cur_dev.setObjectName("label_cur_dev")
        self.plainTextEdit_Memo = QtWidgets.QPlainTextEdit(self.frame_monitoring)
        self.plainTextEdit_Memo.setGeometry(QtCore.QRect(30, 510, 1301, 221))
        self.plainTextEdit_Memo.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 10pt \"Times New Roman\";\n"
"color:green;")
        self.plainTextEdit_Memo.setPlainText("")
        self.plainTextEdit_Memo.setObjectName("plainTextEdit_Memo")
        self.transl_but = QtWidgets.QPushButton(self.frame_monitoring)
        self.transl_but.setGeometry(QtCore.QRect(20, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.transl_but.setFont(font)
        self.transl_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.transl_but.setIconSize(QtCore.QSize(20, 30))
        self.transl_but.setFlat(False)
        self.transl_but.setObjectName("transl_but")
        self.generator_but = QtWidgets.QPushButton(self.frame_monitoring)
        self.generator_but.setGeometry(QtCore.QRect(180, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.generator_but.setFont(font)
        self.generator_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.generator_but.setIconSize(QtCore.QSize(20, 30))
        self.generator_but.setFlat(False)
        self.generator_but.setObjectName("generator_but")
        self.status_but = QtWidgets.QPushButton(self.frame_monitoring)
        self.status_but.setGeometry(QtCore.QRect(340, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.status_but.setFont(font)
        self.status_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.status_but.setIconSize(QtCore.QSize(20, 30))
        self.status_but.setFlat(False)
        self.status_but.setObjectName("status_but")
        self.reboot_but = QtWidgets.QPushButton(self.frame_monitoring)
        self.reboot_but.setGeometry(QtCore.QRect(500, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.reboot_but.setFont(font)
        self.reboot_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.reboot_but.setIconSize(QtCore.QSize(20, 30))
        self.reboot_but.setFlat(False)
        self.reboot_but.setObjectName("reboot_but")
        self.update_but = QtWidgets.QPushButton(self.frame_monitoring)
        self.update_but.setGeometry(QtCore.QRect(1150, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.update_but.setFont(font)
        self.update_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.update_but.setIconSize(QtCore.QSize(20, 30))
        self.update_but.setFlat(False)
        self.update_but.setObjectName("update_but")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1341, 751))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"background:white;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"border:transperant;\n"
"border-bottom:1px solid black;\n"
"font-family:times;\n"
"font-size:16px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setEnabled(False)
        self.frame_2.setGeometry(QtCore.QRect(70, 10, 1201, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QFrame\n"
"{\n"
"background:#333;\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"border:transperant;\n"
"border-bottom:1px solid black;\n"
"font-family:times;\n"
"font-size:16px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.head_label = QtWidgets.QLabel(self.frame_2)
        self.head_label.setEnabled(False)
        self.head_label.setGeometry(QtCore.QRect(10, 10, 1161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.head_label.setFont(font)
        self.head_label.setStyleSheet("font: 75 18pt \"Times New Roman\";")
        self.head_label.setTextFormat(QtCore.Qt.PlainText)
        self.head_label.setAlignment(QtCore.Qt.AlignCenter)
        self.head_label.setWordWrap(False)
        self.head_label.setObjectName("head_label")
        self.Name_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.Name_lineEdit.setGeometry(QtCore.QRect(52, 190, 191, 22))
        font = QtGui.QFont()
        font.setFamily("times")
        font.setPointSize(-1)
        self.Name_lineEdit.setFont(font)
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.Ip_lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.Ip_lineEdit_2.setGeometry(QtCore.QRect(52, 240, 191, 22))
        self.Ip_lineEdit_2.setObjectName("Ip_lineEdit_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(320, 180, 941, 331))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(188)
        self.save_but = QtWidgets.QPushButton(self.frame)
        self.save_but.setGeometry(QtCore.QRect(30, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.save_but.setFont(font)
        self.save_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.save_but.setIconSize(QtCore.QSize(20, 30))
        self.save_but.setFlat(False)
        self.save_but.setObjectName("save_but")
        self.add_but = QtWidgets.QPushButton(self.frame)
        self.add_but.setGeometry(QtCore.QRect(160, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.add_but.setFont(font)
        self.add_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.add_but.setIconSize(QtCore.QSize(20, 30))
        self.add_but.setFlat(False)
        self.add_but.setObjectName("add_but")
        self.cancel_but = QtWidgets.QPushButton(self.frame)
        self.cancel_but.setGeometry(QtCore.QRect(30, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.cancel_but.setFont(font)
        self.cancel_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.cancel_but.setIconSize(QtCore.QSize(20, 30))
        self.cancel_but.setFlat(False)
        self.cancel_but.setObjectName("cancel_but")
        self.del_but = QtWidgets.QPushButton(self.frame)
        self.del_but.setGeometry(QtCore.QRect(160, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.del_but.setFont(font)
        self.del_but.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:20;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:pressed { background-color: lightblue; }")
        self.del_but.setIconSize(QtCore.QSize(20, 30))
        self.del_but.setFlat(False)
        self.del_but.setObjectName("del_but")
        self.Port_lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.Port_lineEdit_3.setGeometry(QtCore.QRect(52, 290, 191, 22))
        self.Port_lineEdit_3.setObjectName("Port_lineEdit_3")
        self.Login_lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.Login_lineEdit_4.setGeometry(QtCore.QRect(52, 340, 191, 22))
        self.Login_lineEdit_4.setObjectName("Login_lineEdit_4")
        self.Passw_lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.Passw_lineEdit_5.setGeometry(QtCore.QRect(52, 390, 191, 22))
        self.Passw_lineEdit_5.setObjectName("Passw_lineEdit_5")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_8.setText(_translate("Dialog", "Обновить данные"))
        self.label_cur_dev.setText(_translate("Dialog", "Текущее устройство: НЗНП 10.8.0.12"))
        self.transl_but.setText(_translate("Dialog", "Стоп Трансляции"))
        self.generator_but.setText(_translate("Dialog", "Стоп Генерации"))
        self.status_but.setText(_translate("Dialog", "Статус служб"))
        self.reboot_but.setText(_translate("Dialog", "Перезапуск спуфера"))
        self.update_but.setText(_translate("Dialog", "Обновить данные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Панель мониторинга"))
        self.head_label.setText(_translate("Dialog", "SSH Monitoring Settings"))
        self.Name_lineEdit.setText(_translate("Dialog", "Name"))
        self.Ip_lineEdit_2.setText(_translate("Dialog", "IP Adress"))
        self.save_but.setText(_translate("Dialog", "Сохранить"))
        self.add_but.setText(_translate("Dialog", "Добавить"))
        self.cancel_but.setText(_translate("Dialog", "Отмена"))
        self.del_but.setText(_translate("Dialog", "Удалить"))
        self.Port_lineEdit_3.setText(_translate("Dialog", "Port"))
        self.Login_lineEdit_4.setText(_translate("Dialog", "Login"))
        self.Passw_lineEdit_5.setText(_translate("Dialog", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Панель настроек"))
